// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Test2Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void test2() {
    driver.Navigate().GoToUrl("http://20.50.171.10:8080/");
    driver.Manage().Window.Size = new System.Drawing.Size(1152, 620);
    driver.FindElement(By.CssSelector(".ownerTab > .caret")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(2) > a")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Dima");
    driver.FindElement(By.Id("lastName")).Click();
    driver.FindElement(By.Id("lastName")).SendKeys("Horbenko");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("adress5");
    driver.FindElement(By.CssSelector(".form-horizontal")).Click();
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("Zhitomir");
    driver.FindElement(By.Id("telephone")).Click();
    driver.FindElement(By.Id("telephone")).SendKeys("012312345");
    driver.FindElement(By.CssSelector(".addOwner")).Click();
  }
}
